name: Publish Site on GitHub Pages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: enriikke/gatsby-gh-pages-action@v2
        env:
          AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN  }}
          AIRTABLE_SCD_BASE_ID: ${{ secrets.AIRTABLE_SCD_BASE_ID }}
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
